### PR TITLE
repo: initializing repo structure

### PR DESCRIPTION
**Pull request by bzalugas**
Just initializing repo structure

### CODE REVIEW

**Review by fidwig — CHANGES_REQUESTED** [review]
NOPE. It is missing:
- strcmp
- free split
- ur mom
AND THATS ABOUT IT
BYEEE   --fidwiz

**Comment by bzalugas** [comment]
I made changes you requested bro

**Review by fidwig — CHANGES_REQUESTED** [review]
SUBMODULES NO MORE !
FREE LIBFT !
BYEEEEE  -fidwizzzzxccxzcz

**Review by fidwig — APPROVED** [review]
# PERFECT CHANGES
**you're so strong**
- baza

**Pull request merged**
